In [62]:
# Import libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from datetime import datetime

In [63]:
import os
print("Current Working Directory:", os.getcwd())

Current Working Directory: c:\Users\USER\Desktop\nyc-airbnb-market-explorer\src

In [64]:
# This goes up one level from where this notebook is running
project_root = os.path.dirname(os.getcwd())
file_path = os.path.join(project_root, 'data', 'raw', 'listings.csv')

# Load the dataset safely
df_listings = pd.read_csv(file_path)

C:\Users\USER\AppData\Local\Temp\ipykernel_12208\2762424658.py:6: DtypeWarning: Columns (0: license) have mixed types. Specify dtype option on import or set low_memory=False.
  df_listings = pd.read_csv(file_path)

In [65]:
#Get the first values of the dataframe and assess what it contains
df_listings.head()

,id,listing_url,scrape_id,last_scraped,name,description,neighborhood_overview,picture_url,host_id,host_url,...,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,2595.0,https://www.airbnb.com/rooms/2595,2.022060e+13,04/06/2022,Skylit Midtown Castle,"Beautiful, spacious skylit studio in the heart...",Centrally located in the heart of Manhattan ju...,https://a0.muscache.com/pictures/f0813a11-40b2...,2845,https://www.airbnb.com/users/show/2845,...,4.79,4.86,4.41,NaN,f,3,3,0,0,0.31
1,5121.0,https://www.airbnb.com/rooms/5121,2.022060e+13,04/06/2022,BlissArtsSpace!,One room available for rent in a 2 bedroom apt...,NaN,https://a0.muscache.com/pictures/2090980c-b68e...,7356,https://www.airbnb.com/users/show/7356,...,4.91,4.47,4.52,NaN,f,2,0,2,0,0.32
2,5136.0,https://www.airbnb.com/rooms/5136,2.022060e+13,04/06/2022,"Spacious Brooklyn Duplex, Patio + Garden",We welcome you to stay in our lovely 2 br dupl...,NaN,https://a0.muscache.com/pictures/miso/Hosting-...,7378,https://www.airbnb.com/users/show/7378,...,5.00,4.50,5.00,NaN,f,1,1,0,0,0.02
3,5178.0,https://www.airbnb.com/rooms/5178,2.022060e+13,04/06/2022,Large Furnished Room Near B'way,Please don’t expect the luxury here just a bas...,"Theater district, many restaurants around here.",https://a0.muscache.com/pictures/12065/f070997...,8967,https://www.airbnb.com/users/show/8967,...,4.44,4.87,4.39,NaN,f,1,0,1,0,3.37
4,5203.0,https://www.airbnb.com/rooms/5203,2.022060e+13,03/06/2022,Cozy Clean Guest Room - Family Apt,"Our best guests are seeking a safe, clean, spa...",Our neighborhood is full of restaurants and ca...,https://a0.muscache.com/pictures/103776/b37157...,7490,https://www.airbnb.com/users/show/7490,...,4.95,4.94,4.92,NaN,f,1,0,1,0,0.76

In [66]:
# Get the information about the data
df_listings.info()

<class 'pandas.DataFrame'>
RangeIndex: 37410 entries, 0 to 37409
Data columns (total 74 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   id                                            37410 non-null  float64
 1   listing_url                                   37410 non-null  str
 2   scrape_id                                     37410 non-null  float64
 3   last_scraped                                  37410 non-null  str
 4   name                                          37396 non-null  str
 5   description                                   36523 non-null  str
 6   neighborhood_overview                         22430 non-null  str
 7   picture_url                                   37410 non-null  str
 8   host_id                                       37410 non-null  int64
 9   host_url                                      37410 non-null  str
 10  host_name                                     37344 non-null  str
 11  host_since                                    37344 non-null  str
 12  host_location                                 37247 non-null  str
 13  host_about                                    21054 non-null  str
 14  host_response_time                            24200 non-null  str
 15  host_response_rate                            24200 non-null  str
 16  host_acceptance_rate                          25678 non-null  str
 17  host_is_superhost                             37344 non-null  str
 18  host_thumbnail_url                            37344 non-null  str
 19  host_picture_url                              37344 non-null  str
 20  host_neighbourhood                            29868 non-null  str
 21  host_listings_count                           37344 non-null  float64
 22  host_total_listings_count                     37344 non-null  float64
 23  host_verifications                            37344 non-null  str
 24  host_has_profile_pic                          37344 non-null  str
 25  host_identity_verified                        37344 non-null  str
 26  neighbourhood                                 22431 non-null  str
 27  neighbourhood_cleansed                        37410 non-null  str
 28  neighbourhood_group_cleansed                  37410 non-null  str
 29  latitude                                      37410 non-null  float64
 30  longitude                                     37410 non-null  float64
 31  property_type                                 37410 non-null  str
 32  room_type                                     37410 non-null  str
 33  accommodates                                  37410 non-null  int64
 34  bathrooms                                     0 non-null      float64
 35  bathrooms_text                                37329 non-null  str
 36  bedrooms                                      33756 non-null  float64
 37  beds                                          36509 non-null  float64
 38  amenities                                     37410 non-null  str
 39  price                                         37410 non-null  str
 40  minimum_nights                                37410 non-null  int64
 41  maximum_nights                                37410 non-null  int64
 42  minimum_minimum_nights                        37395 non-null  float64
 43  maximum_minimum_nights                        37395 non-null  float64
 44  minimum_maximum_nights                        37395 non-null  float64
 45  maximum_maximum_nights                        37395 non-null  float64
 46  minimum_nights_avg_ntm                        37395 non-null  float64
 47  maximum_nights_avg_ntm                        37395 non-null  float64
 48  calendar_updated                              0 non-null      float64
 49  has_availability                              37410 non-null  str
 50  availability_30                               37410 non-null  int64
 51  availability_60                               37410 non-null  int64
 52  availability_90                               37410 non-null  int64
 53  availability_365                              37410 non-null  int64
 54  calendar_last_scraped                         37410 non-null  str
 55  number_of_reviews                             37410 non-null  int64
 56  number_of_reviews_ltm                         37410 non-null  int64
 57  number_of_reviews_l30d                        37410 non-null  int64
 58  first_review                                  29461 non-null  str
 59  last_review                                   29461 non-null  str
 60  review_scores_rating                          29461 non-null  float64
 61  review_scores_accuracy                        28982 non-null  float64
 62  review_scores_cleanliness                     28992 non-null  float64
 63  review_scores_checkin                         28978 non-null  float64
 64  review_scores_communication                   28987 non-null  float64
 65  review_scores_location                        28975 non-null  float64
 66  review_scores_value                           28975 non-null  float64
 67  license                                       4 non-null      str
 68  instant_bookable                              37410 non-null  str
 69  calculated_host_listings_count                37410 non-null  int64
 70  calculated_host_listings_count_entire_homes   37410 non-null  int64
 71  calculated_host_listings_count_private_rooms  37410 non-null  int64
 72  calculated_host_listings_count_shared_rooms   37410 non-null  int64
 73  reviews_per_month                             29461 non-null  float64
dtypes: float64(24), int64(15), str(35)
memory usage: 21.1 MB

In [67]:
#Basic statistics in the dataset
df_listings.describe()

,id,scrape_id,host_id,host_listings_count,host_total_listings_count,latitude,longitude,accommodates,bathrooms,bedrooms,...,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
count,3.741000e+04,3.741000e+04,3.741000e+04,37344.000000,37344.000000,37410.000000,37410.000000,37410.000000,0.0,33756.000000,...,28992.000000,28978.000000,28987.000000,28975.000000,28975.000000,37410.000000,37410.000000,37410.000000,37410.000000,29461.000000
mean,6.100385e+16,2.022060e+13,1.237140e+08,63.811509,63.811509,40.729308,-73.946171,2.904918,NaN,1.354219,...,4.626467,4.815760,4.807910,4.747036,4.649349,15.114782,9.396685,5.600508,0.051270,1.166622
std,1.806040e+17,0.000000e+00,1.382397e+08,400.332606,400.332606,0.058041,0.056701,1.964525,NaN,0.734038,...,0.549928,0.416488,0.443218,0.405745,0.497136,50.717311,45.421795,23.806312,0.492768,1.851005
min,2.595000e+03,2.022060e+13,2.438000e+03,0.000000,0.000000,40.504560,-74.269520,0.000000,NaN,1.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.010000
25%,1.470053e+07,2.022060e+13,1.293966e+07,1.000000,1.000000,40.688260,-73.983518,2.000000,NaN,1.000000,...,4.500000,4.800000,4.800000,4.670000,4.560000,1.000000,0.000000,0.000000,0.000000,0.130000
50%,3.484341e+07,2.022060e+13,5.372558e+07,1.000000,1.000000,40.724885,-73.953794,2.000000,NaN,1.000000,...,4.800000,4.950000,4.960000,4.860000,4.780000,1.000000,1.000000,0.000000,0.000000,0.490000
75%,5.018400e+07,2.022060e+13,2.093738e+08,3.000000,3.000000,40.763380,-73.926340,4.000000,NaN,1.000000,...,5.000000,5.000000,5.000000,5.000000,4.970000,3.000000,1.000000,1.000000,0.000000,1.640000
max,6.412410e+17,2.022060e+13,4.623937e+08,3404.000000,3404.000000,40.928340,-73.693210,16.000000,NaN,15.000000,...,5.000000,5.000000,5.000000,5.000000,5.000000,391.000000,391.000000,190.000000,11.000000,81.260000

In [68]:
# Check for missing values
df_listings.isnull().sum()

id                                                 0
listing_url                                        0
scrape_id                                          0
last_scraped                                       0
name                                              14
                                                ...
calculated_host_listings_count                     0
calculated_host_listings_count_entire_homes        0
calculated_host_listings_count_private_rooms       0
calculated_host_listings_count_shared_rooms        0
reviews_per_month                               7949
Length: 74, dtype: int64

In [69]:
#Data types in the data
df_listings.dtypes

id                                              float64
listing_url                                         str
scrape_id                                       float64
last_scraped                                        str
name                                                str
                                                 ...
calculated_host_listings_count                    int64
calculated_host_listings_count_entire_homes       int64
calculated_host_listings_count_private_rooms      int64
calculated_host_listings_count_shared_rooms       int64
reviews_per_month                               float64
Length: 74, dtype: object

In [70]:
#Unique values in key columns
print(f"Neighborhoods: {df_listings['neighbourhood'].nunique()}")
print(f"Room types: {df_listings['room_type'].unique()}")

Neighborhoods: 224
Room types: <StringArray>
['Entire home/apt', 'Private room', 'Hotel room', 'Shared room']
Length: 4, dtype: str

In [ ]:
#Initial exploration
df_listings.to_csv('../data/raw/listings.csv', index=False)

: